image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
- port: 8000
  onOpen: ignore
  visibility: public

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
- init: poetry install --no-root
- init: mkdir -p /workspace/data
  command: mongod --dbpath /workspace/data --bind_ip 127.0.0.1

vscode:
  extensions:
    - ms-python.python
    - mongodb.mongodb-vscode
    - davidanson.vscode-markdownlint
    - ms-azuretools.vscode-docker
    - charliermarsh.ruff
