version: '3.7'
services:
  api:
    build: .
    ports:
      - 8000:8000
    environment:
      - AUTH0_AUDIENCE
      - AUTH0_ISSUER
      - AUTH0_PEM
      - MONGODB_URI
      - MONGODB_DB
      - SENTRY_DSN
      - SENTRY_ENVIRONMENT
      - EBL_AI_API
    volumes:
      - ./ebl:/usr/src/ebl/ebl
    restart: always
  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ebl-mongodb:/data/db
    environment:
      - MONGO_INITDB_DATABASE=ebl
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    secrets:
      - source: mongo_users
        target: /docker-entrypoint-initdb.d/create-users.js
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    links:
      - mongo
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_SITE_GRIDFS_ENABLED=true
volumes:
  ebl-mongodb:
    driver: local
secrets:
  mongo_users:
    file: ./docker-entrypoint-initdb.d/create-users.js