?start: label

?label: column_label | surface_label

column_label: ROMAN_NUMERAL status
ROMAN_NUMERAL: /[ivx]+/

surface_label: surface status
surface: OBVERSE | REVERSE | BOTTOM | EDGE | LEFT | RIGHT | TOP
OBVERSE: "o"
REVERSE:"r"
BOTTOM: "b.e."
EDGE: "e."
LEFT: "l.e."
RIGHT: "r.e."
TOP: "t.e."

status: (PRIME | UNCERTAIN | CORRECTION | COLLATION)*
PRIME: "'"
UNCERTAIN: "?"
CORRECTION: "!"
COLLATION: "*"
