from typing import Sequence

LIST_ROUTE_SEGMENT = "all"
BY_ID_ROUTE_SEGMENT = "by-id"
EMPTY_IDENTIFIER = ""

RESERVED_REALIA_IDS: Sequence[str] = (LIST_ROUTE_SEGMENT, EMPTY_IDENTIFIER)
RESERVED_REALIA_ID_PREFIXES: Sequence[str] = (f"{BY_ID_ROUTE_SEGMENT}/",)
