from typing import Mapping, Type, Union

from marshmallow import Schema
from marshmallow_oneofschema.one_of_schema import OneOfSchema

from ebl.transliteration.application.token_schemas_enclosures import (
    AccidentalOmissionSchema,
    BaseTokenSchema,
    BrokenAwaySchema,
    DocumentOrientedGlossSchema,
    EmendationSchema,
    EnclosureSchema,
    ErasureSchema,
    IntentionalOmissionSchema,
    LanguageShiftSchema,
    PerhapsBrokenAwaySchema,
    RemovalSchema,
    ValueTokenSchema,
)
from ebl.transliteration.application.token_schemas_tokens import (
    ColumnSchema,
    CommentaryProtocolSchema,
    DividerSchema,
    EgyptianMetricalFeetSeparatorSchema,
    InWordNewlineSchema,
    JoinerSchema,
    TabulationSchema,
    UnclearSignSchema,
    UnidentifiedSignSchema,
    UnknownNumberOfSignsSchema,
    WordOmittedSchema,
)
from ebl.transliteration.application.token_schemas_signs import (
    CompoundGraphemeSchema,
    DeterminativeSchema,
    GlossSchema,
    GraphemeSchema,
    LineBreakSchema,
    LinguisticGlossSchema,
    LogogramSchema,
    NamedSignSchema,
    NumberSchema,
    PhoneticGlossSchema,
    ReadingSchema,
    VariantSchema,
)
from ebl.transliteration.application.token_schemas_words import (
    AkkadianWordSchema,
    BaseWordSchema,
    BreakSchema,
    CaesuraSchema,
    GreekLetterSchema,
    GreekWordSchema,
    LoneDeterminativeSchema,
    MetricalFootSeparatorSchema,
    WordSchema,
)

WORD_SCHEMAS: Mapping[str, Type[BaseWordSchema]] = {
    "Word": WordSchema,
    "LoneDeterminative": LoneDeterminativeSchema,
    "AkkadianWord": AkkadianWordSchema,
    "GreekWord": GreekWordSchema,
}


class OneOfWordSchema(OneOfSchema):
    type_field = "type"
    type_schemas: Mapping[str, Union[Type[Schema], Schema]] = WORD_SCHEMAS


class OneOfTokenSchema(OneOfSchema):
    type_field = "type"
    type_schemas: Mapping[str, Union[Type[Schema], Schema]] = {
        **WORD_SCHEMAS,
        "Token": ValueTokenSchema,
        "ValueToken": ValueTokenSchema,
        "LanguageShift": LanguageShiftSchema,
        "DocumentOrientedGloss": DocumentOrientedGlossSchema,
        "BrokenAway": BrokenAwaySchema,
        "PerhapsBrokenAway": PerhapsBrokenAwaySchema,
        "AccidentalOmission": AccidentalOmissionSchema,
        "IntentionalOmission": IntentionalOmissionSchema,
        "Removal": RemovalSchema,
        "Emendation": EmendationSchema,
        "Erasure": ErasureSchema,
        "UnknownNumberOfSigns": UnknownNumberOfSignsSchema,
        "WordOmitted": WordOmittedSchema,
        "Tabulation": TabulationSchema,
        "CommentaryProtocol": CommentaryProtocolSchema,
        "Divider": DividerSchema,
        "Column": ColumnSchema,
        "Variant": VariantSchema,
        "UnidentifiedSign": UnidentifiedSignSchema,
        "UnclearSign": UnclearSignSchema,
        "Joiner": JoinerSchema,
        "InWordNewline": InWordNewlineSchema,
        "Reading": ReadingSchema,
        "Logogram": LogogramSchema,
        "Number": NumberSchema,
        "CompoundGrapheme": CompoundGraphemeSchema,
        "Grapheme": GraphemeSchema,
        "Determinative": DeterminativeSchema,
        "PhoneticGloss": PhoneticGlossSchema,
        "LinguisticGloss": LinguisticGlossSchema,
        "EgyptianMetricalFeetSeparator": EgyptianMetricalFeetSeparatorSchema,
        "LineBreak": LineBreakSchema,
        "Caesura": CaesuraSchema,
        "MetricalFootSeparator": MetricalFootSeparatorSchema,
        "GreekLetter": GreekLetterSchema,
    }


__all__ = [
    "AccidentalOmissionSchema",
    "AkkadianWordSchema",
    "BaseTokenSchema",
    "BaseWordSchema",
    "BreakSchema",
    "BrokenAwaySchema",
    "CaesuraSchema",
    "ColumnSchema",
    "CommentaryProtocolSchema",
    "CompoundGraphemeSchema",
    "DeterminativeSchema",
    "DividerSchema",
    "DocumentOrientedGlossSchema",
    "EgyptianMetricalFeetSeparatorSchema",
    "EmendationSchema",
    "EnclosureSchema",
    "ErasureSchema",
    "GlossSchema",
    "GraphemeSchema",
    "GreekLetterSchema",
    "GreekWordSchema",
    "InWordNewlineSchema",
    "IntentionalOmissionSchema",
    "JoinerSchema",
    "LanguageShiftSchema",
    "LineBreakSchema",
    "LinguisticGlossSchema",
    "LogogramSchema",
    "LoneDeterminativeSchema",
    "MetricalFootSeparatorSchema",
    "NamedSignSchema",
    "NumberSchema",
    "OneOfTokenSchema",
    "OneOfWordSchema",
    "PerhapsBrokenAwaySchema",
    "PhoneticGlossSchema",
    "ReadingSchema",
    "RemovalSchema",
    "TabulationSchema",
    "UnclearSignSchema",
    "UnidentifiedSignSchema",
    "UnknownNumberOfSignsSchema",
    "ValueTokenSchema",
    "VariantSchema",
    "WORD_SCHEMAS",
    "WordOmittedSchema",
    "WordSchema",
]
