genres = (
    ("UNCERTAIN",),
    ("ARCHIVAL",),
    ("ARCHIVAL", "Administrative"),
    ("ARCHIVAL", "Administrative", "Lists"),
    ("ARCHIVAL", "Administrative", "Lists", "One Entry"),
    ("ARCHIVAL", "Administrative", "Lists", "Multientry"),
    ("ARCHIVAL", "Administrative", "Memos"),
    ("ARCHIVAL", "Administrative", "Inventories"),
    ("ARCHIVAL", "Administrative", "Inventories", "Balanced Accounts"),
    ("ARCHIVAL", "Administrative", "Inventories", "Basket Labels"),
    ("ARCHIVAL", "Administrative", "Receipts"),
    ("ARCHIVAL", "Administrative", "Receipts", "Income"),
    ("ARCHIVAL", "Administrative", "Expenditure"),
    ("ARCHIVAL", "Administrative", "Expenditure", "Messenger Text"),
    ("ARCHIVAL", "Legal"),
    ("ARCHIVAL", "Legal", "Debt Note, Loan"),
    ("ARCHIVAL", "Legal", "Decree"),
    ("ARCHIVAL", "Legal", "Judicial"),
    ("ARCHIVAL", "Legal", "Judicial", "Court Case"),
    ("ARCHIVAL", "Legal", "Sale"),
    ("ARCHIVAL", "Legal", "Transfer of Properties, Other"),
    ("ARCHIVAL", "Legal", "Transfer of Properties, Other", "Inheritance"),
    ("ARCHIVAL", "Legal", "Transfer of Properties, Other", "Adoption"),
    ("ARCHIVAL", "Legal", "Transfer of Properties, Other", "Dowry"),
    ("ARCHIVAL", "Legal", "Transfer of Properties, Other", "Exchange"),
    ("ARCHIVAL", "Legal", "Treaty"),
    ("ARCHIVAL", "Letter"),
    ("ARCHIVAL", "Letter", "Extispicy Query"),
    ("ARCHIVAL", "Letter", "Prophecy"),
    ("ARCHIVAL", "Letter", "Report"),
    ("CANONICAL",),
    ("CANONICAL", "Catalogues"),
    ("CANONICAL", "Divination"),
    ("CANONICAL", "Divination", "Celestial"),
    ("CANONICAL", "Divination", "Extispicy"),
    ("CANONICAL", "Divination", "Hemerology"),
    ("CANONICAL", "Divination", "Oracular Question"),
    ("CANONICAL", "Divination", "Physiognomy"),
    ("CANONICAL", "Divination", "Teratological"),
    ("CANONICAL", "Divination", "Terrestrial"),
    ("CANONICAL", "Divination", "Other (Dreams, Birds, etc.)"),
    ("CANONICAL", "Historiography"),
    ("CANONICAL", "Historiography", "Chronicles"),
    ("CANONICAL", "Historiography", "Legal"),
    ("CANONICAL", "Historiography", "Letter"),
    ("CANONICAL", "Historiography", "King Lists (incl. Eponym Lists)"),
    ("CANONICAL", "Lexicography"),
    ("CANONICAL", "Lexicography", "Acrographic word list"),
    ("CANONICAL", "Lexicography", "God List"),
    ("CANONICAL", "Lexicography", "Grammatical"),
    ("CANONICAL", "Lexicography", "Plant List"),
    ("CANONICAL", "Lexicography", "Sign exercise"),
    ("CANONICAL", "Lexicography", "Sign list"),
    ("CANONICAL", "Lexicography", "Synonym List"),
    ("CANONICAL", "Lexicography", "Thematic Word Lists"),
    ("CANONICAL", "Lexicography", "Vocabularies"),
    ("CANONICAL", "Literature"),
    ("CANONICAL", "Literature", "Monologue and dialogue"),
    ("CANONICAL", "Literature", "Monologue and dialogue", "Debate poems"),
    ("CANONICAL", "Literature", "Monologue and dialogue", "Fables"),
    ("CANONICAL", "Literature", "Monologue and dialogue", "Instructions"),
    ("CANONICAL", "Literature", "Monologue and dialogue", "Love"),
    ("CANONICAL", "Literature", "Monologue and dialogue", "Monologues"),
    ("CANONICAL", "Literature", "Monologue and dialogue", "Proverbs"),
    ("CANONICAL", "Literature", "Monologue and dialogue", "Scribal"),
    ("CANONICAL", "Literature", "Hymns"),
    ("CANONICAL", "Literature", "Hymns", "Divine"),
    ("CANONICAL", "Literature", "Hymns", "Royal"),
    ("CANONICAL", "Literature", "Hymns", "Temples"),
    ("CANONICAL", "Literature", "Lamentations"),
    ("CANONICAL", "Literature", "Narrative"),
    ("CANONICAL", "Magic"),
    ("CANONICAL", "School Tablet"),
    ("CANONICAL", "Technical"),
    ("CANONICAL", "Technical", "Astronomy"),
    ("CANONICAL", "Technical", "Commentary"),
    ("CANONICAL", "Technical", "Mathematics"),
    ("CANONICAL", "Technical", "Medicine"),
    ("CANONICAL", "Technical", "Medicine", "Diagnostic and Prognostic"),
    ("CANONICAL", "Technical", "Medicine", "Therapeutic"),
    ("CANONICAL", "Technical", "Procedures"),
    ("CANONICAL", "Technical", "Ritual texts"),
    ("MONUMENTAL",),
    ("MONUMENTAL", "Building"),
    ("MONUMENTAL", "Dedication"),
    ("MONUMENTAL", "Legal"),
    ("MONUMENTAL", "Narrative"),
    ("MONUMENTAL", "Representative (personalia)"),
    ("MONUMENTAL", "Seal inscriptions"),
    ("OTHER",),
    ("OTHER", "Fake"),
    ("OTHER", "Uncertain"),
)
