genres = (
    ("ARCHIVAL",),
    ("ARCHIVAL", "Administrative"),
    ("ARCHIVAL", "Administrative", "Expenditure"),
    ("ARCHIVAL", "Administrative", "Expenditure", "Messenger Text"),
    ("ARCHIVAL", "Administrative", "Inventories"),
    ("ARCHIVAL", "Administrative", "Inventories", "Balanced Accounts"),
    ("ARCHIVAL", "Administrative", "Inventories", "Basket Labels"),
    ("ARCHIVAL", "Administrative", "Lists"),
    ("ARCHIVAL", "Administrative", "Lists", "Multientry"),
    ("ARCHIVAL", "Administrative", "Lists", "One Entry"),
    ("ARCHIVAL", "Administrative", "Memos"),
    ("ARCHIVAL", "Administrative", "Receipts"),
    ("ARCHIVAL", "Administrative", "Receipts", "Income"),
    ("ARCHIVAL", "Legal"),
    ("ARCHIVAL", "Legal", "Debt Note, Loan"),
    ("ARCHIVAL", "Legal", "Decree"),
    ("ARCHIVAL", "Legal", "Judicial"),
    ("ARCHIVAL", "Legal", "Judicial", "Court Case"),
    ("ARCHIVAL", "Legal", "Sale"),
    ("ARCHIVAL", "Legal", "Transfer of Properties, Other"),
    ("ARCHIVAL", "Legal", "Transfer of Properties, Other", "Adoption"),
    ("ARCHIVAL", "Legal", "Transfer of Properties, Other", "Dowry"),
    ("ARCHIVAL", "Legal", "Transfer of Properties, Other", "Exchange"),
    ("ARCHIVAL", "Legal", "Transfer of Properties, Other", "Inheritance"),
    ("ARCHIVAL", "Legal", "Treaty"),
    ("ARCHIVAL", "Letter"),
    ("ARCHIVAL", "Letter", "Extispicy Query"),
    ("ARCHIVAL", "Letter", "Prophecy"),
    ("ARCHIVAL", "Letter", "Report"),
    ("CANONICAL",),
    ("CANONICAL", "Catalogues"),
    ("CANONICAL", "Catalogues", "Catalogue of Texts and Authors"),
    ("CANONICAL", "Catalogues", "Kalûtu catalogue"),
    ("CANONICAL", "Divination"),
    ("CANONICAL", "Divination", "Celestial"),
    ("CANONICAL", "Divination", "Celestial", "Rikis Gerri"),
    ("CANONICAL", "Divination", "Celestial", "Enūma Anu Enlil"),
    ("CANONICAL", "Divination", "Celestial", "Enūma Anu Enlil", "Adad (EAE 36–49)"),
    ("CANONICAL", "Divination", "Celestial", "Enūma Anu Enlil", "Ištar (EAE 50–68)"),
    ("CANONICAL", "Divination", "Celestial", "Enūma Anu Enlil", "Šamaš (EAE 23–35)"),
    ("CANONICAL", "Divination", "Celestial", "Enūma Anu Enlil", "Sîn (EAE 1–22)"),
    ("CANONICAL", "Divination", "Celestial", "Sîn ina tāmartīšu"),
    ("CANONICAL", "Divination", "Diviner’s manual"),
    ("CANONICAL", "Divination", "Extispicy"),
    ("CANONICAL", "Divination", "Extispicy", "Bārûtu"),
    ("CANONICAL", "Divination", "Extispicy", "Bārûtu", "1. Isru"),
    ("CANONICAL", "Divination", "Extispicy", "Bārûtu", "2. Tirānu"),
    ("CANONICAL", "Divination", "Extispicy", "Bārûtu", "3. Manzāzu"),
    ("CANONICAL", "Divination", "Extispicy", "Bārûtu", "4. Padānu"),
    ("CANONICAL", "Divination", "Extispicy", "Bārûtu", "5. Pān tākalti"),
    ("CANONICAL", "Divination", "Extispicy", "Bārûtu", "6. Martu"),
    ("CANONICAL", "Divination", "Extispicy", "Bārûtu", "7. Ubānu"),
    ("CANONICAL", "Divination", "Extispicy", "Bārûtu", "8. Kakku"),
    ("CANONICAL", "Divination", "Extispicy", "Bārûtu", "9. Ḫašû"),
    ("CANONICAL", "Divination", "Extispicy", "Bārûtu", "10. Multābiltu"),
    ("CANONICAL", "Divination", "Extispicy", "Combined Protases"),
    (
        "CANONICAL",
        "Divination",
        "Extispicy",
        "DUB ḪA.LA and the Calculation of the Stipulated Term",
    ),
    ("CANONICAL", "Divination", "Extispicy", "Niṣirti bārûti"),
    ("CANONICAL", "Divination", "Extispicy", "Orientation tablets/Liver models"),
    ("CANONICAL", "Divination", "Extispicy", "Protases in Context"),
    ("CANONICAL", "Divination", "Hemerology"),
    ("CANONICAL", "Divination", "Hemerology", "Babylonian Almanac"),
    ("CANONICAL", "Divination", "Hemerology", "Eclipse Hemerology"),
    ("CANONICAL", "Divination", "Hemerology", "Hemerology for Nazimaruttaš"),
    ("CANONICAL", "Divination", "Hemerology", "Hemerology of Assur"),
    ("CANONICAL", "Divination", "Hemerology", "Inbu bēl arḫi"),
    ("CANONICAL", "Divination", "Hemerology", "Iqqur īpuš"),
    ("CANONICAL", "Divination", "Hemerology", "Lists of Lucky Days"),
    ("CANONICAL", "Divination", "Hemerology", "Prostration Hemerology"),
    ("CANONICAL", "Divination", "Hemerology", "Tašrītu Hemerology"),
    ("CANONICAL", "Divination", "Oracular Question"),
    ("CANONICAL", "Divination", "Oracular Question", "Oracle Questions"),
    ("CANONICAL", "Divination", "Other (Dreams, Birds, etc.)"),
    ("CANONICAL", "Divination", "Other (Dreams, Birds, etc.)", "Lecanomancy"),
    (
        "CANONICAL",
        "Divination",
        "Other (Dreams, Birds, etc.)",
        "Omens from the Behavior of the Seer",
    ),
    (
        "CANONICAL",
        "Divination",
        "Other (Dreams, Birds, etc.)",
        "Prodigies of the Fall of Akkad",
    ),
    ("CANONICAL", "Divination", "Other (Dreams, Birds, etc.)", "Šumma immeru"),
    ("CANONICAL", "Divination", "Other (Dreams, Birds, etc.)", "Ziqīqu"),
    ("CANONICAL", "Divination", "Physiognomy"),
    ("CANONICAL", "Divination", "Physiognomy", "Alamdimmû"),
    ("CANONICAL", "Divination", "Physiognomy", "Alamdimmû", "1. Alamdimmû"),
    ("CANONICAL", "Divination", "Physiognomy", "Alamdimmû", "2. Nigdimdimmû"),
    ("CANONICAL", "Divination", "Physiognomy", "Alamdimmû", "3. Kataduggû"),
    (
        "CANONICAL",
        "Divination",
        "Physiognomy",
        "Alamdimmû",
        "4. Šumma sinništu qaqqada rabât",
    ),
    ("CANONICAL", "Divination", "Physiognomy", "Alamdimmû", "5. Šumma liptu"),
    (
        "CANONICAL",
        "Divination",
        "Physiognomy",
        "Alamdimmû",
        "6. Šumma šerʾān pūt imittišu ittenebbi",
    ),
    ("CANONICAL", "Divination", "Physiognomy", "Alamdimmû", "aḫû excerpt series"),
    ("CANONICAL", "Divination", "Physiognomy", "Alamdimmû", "Šumma Ea liballiṭka"),
    ("CANONICAL", "Divination", "Teratological"),
    ("CANONICAL", "Divination", "Teratological", "Šumma izbu Principal Commentary"),
    ("CANONICAL", "Divination", "Teratological", "Šumma izbu"),
    ("CANONICAL", "Divination", "Terrestrial"),
    ("CANONICAL", "Divination", "Terrestrial", "Šumma ālu"),
    ("CANONICAL", "Historiography"),
    ("CANONICAL", "Historiography", "Chronicles"),
    ("CANONICAL", "Historiography", "Chronicles", "Chronicle"),
    ("CANONICAL", "Historiography", "Chronicles", "Dynastic Chronicle"),
    ("CANONICAL", "Historiography", "Chronicles", "Synchronistic History"),
    ("CANONICAL", "Historiography", "King/Eponym Lists"),
    ("CANONICAL", "Historiography", "Legal"),
    ("CANONICAL", "Historiography", "Letter"),
    ("CANONICAL", "Lexicography"),
    ("CANONICAL", "Lexicography", "Acrographic word list"),
    ("CANONICAL", "Lexicography", "Acrographic word list", "Izi"),
    ("CANONICAL", "Lexicography", "God List"),
    ("CANONICAL", "Lexicography", "God List", "An = Anu ša amēli"),
    ("CANONICAL", "Lexicography", "God List", "An = Anum"),
    ("CANONICAL", "Lexicography", "God List", "Weidner God List (Anum)"),
    ("CANONICAL", "Lexicography", "Grammatical"),
    ("CANONICAL", "Lexicography", "Plant List"),
    ("CANONICAL", "Lexicography", "Plant List", "MÚD-UR.MAḪ"),
    ("CANONICAL", "Lexicography", "Plant List", "Šammu šikinšu"),
    ("CANONICAL", "Lexicography", "Plant List", "Uruanna"),
    ("CANONICAL", "Lexicography", "Sign exercise"),
    ("CANONICAL", "Lexicography", "Sign exercise", "Syllable Alphabet A"),
    ("CANONICAL", "Lexicography", "Sign exercise", "Syllable Alphabet B"),
    ("CANONICAL", "Lexicography", "Sign exercise", "TU-TA-TI 1"),
    ("CANONICAL", "Lexicography", "Sign exercise", "TU-TA-TI 2"),
    ("CANONICAL", "Lexicography", "Sign exercise", "TU-TA-TI 3"),
    ("CANONICAL", "Lexicography", "Sign exercise", "TU-TA-TI Varia"),
    ("CANONICAL", "Lexicography", "Sign list"),
    ("CANONICAL", "Lexicography", "Sign list", "Á = idu"),
    ("CANONICAL", "Lexicography", "Sign list", "Aa"),
    ("CANONICAL", "Lexicography", "Sign list", "Diri"),
    ("CANONICAL", "Lexicography", "Sign list", "Ea"),
    ("CANONICAL", "Lexicography", "Sign list", "Paleographic Sa"),
    ("CANONICAL", "Lexicography", "Sign list", "Syllabary Sᵃ"),
    ("CANONICAL", "Lexicography", "Sign list", "Vocabulary Sᵃ"),
    ("CANONICAL", "Lexicography", "Sign list", "Vocabulary Sᵇ"),
    ("CANONICAL", "Lexicography", "Synonym List"),
    ("CANONICAL", "Lexicography", "Synonym List", "An = šamû"),
    ("CANONICAL", "Lexicography", "Synonym List", "An = Anum VII/VIII-X"),
    ("CANONICAL", "Lexicography", "Synonym List", "Malku = šarru (Explicit)"),
    ("CANONICAL", "Lexicography", "Synonym List", "Malku = šarru"),
    ("CANONICAL", "Lexicography", "Thematic Word Lists"),
    ("CANONICAL", "Lexicography", "Thematic Word Lists", "Abnu šikinšu"),
    ("CANONICAL", "Lexicography", "Thematic Word Lists", "Ana ittīšu"),
    ("CANONICAL", "Lexicography", "Thematic Word Lists", "Geographical lists"),
    (
        "CANONICAL",
        "Lexicography",
        "Thematic Word Lists",
        "Geographical lists",
        "Tintir = Babylon",
    ),
    ("CANONICAL", "Lexicography", "Thematic Word Lists", "Götteradressbuch of Aššur"),
    ("CANONICAL", "Lexicography", "Thematic Word Lists", "Great Star List"),
    ("CANONICAL", "Lexicography", "Thematic Word Lists", "List of diseases"),
    ("CANONICAL", "Lexicography", "Thematic Word Lists", "List of diseases"),
    ("CANONICAL", "Lexicography", "Thematic Word Lists", "Lú"),
    ("CANONICAL", "Lexicography", "Thematic Word Lists", "Murgud"),
    ("CANONICAL", "Lexicography", "Thematic Word Lists", "Practical Vocabulary"),
    ("CANONICAL", "Lexicography", "Thematic Word Lists", "Ura"),
    ("CANONICAL", "Lexicography", "Vocabularies"),
    ("CANONICAL", "Lexicography", "Vocabularies", "Antagal"),
    ("CANONICAL", "Lexicography", "Vocabularies", "Emesal-Vocabulary"),
    ("CANONICAL", "Lexicography", "Vocabularies", "Erimhuš"),
    ("CANONICAL", "Lexicography", "Vocabularies", "Nabnītu"),
    ("CANONICAL", "Lexicography", "Vocabularies", "Šarru"),
    ("CANONICAL", "Literature"),
    ("CANONICAL", "Literature", "Hymns"),
    ("CANONICAL", "Literature", "Hymns", "Divine"),
    ("CANONICAL", "Literature", "Hymns", "Divine", "Bulluṭsa-rabi’s Hymn to Gula"),
    ("CANONICAL", "Literature", "Hymns", "Divine", "Great Prayer to Šamaš"),
    ("CANONICAL", "Literature", "Hymns", "Divine", "Hymn to Ištar (“Ištar 2”)"),
    ("CANONICAL", "Literature", "Hymns", "Divine", "Hymn to the Queen of Nippur"),
    ("CANONICAL", "Literature", "Hymns", "Divine", "Kiutu"),
    ("CANONICAL", "Literature", "Hymns", "Divine", "Prayer to Marduk 1"),
    ("CANONICAL", "Literature", "Hymns", "Divine", "Prayer to Marduk 2"),
    ("CANONICAL", "Literature", "Hymns", "Divine", "Šigû Prayer"),
    ("CANONICAL", "Literature", "Hymns", "Divine", "Šuʾila"),
    ("CANONICAL", "Literature", "Hymns", "Divine", "Syncretistic Hymn to Nanāya"),
    (
        "CANONICAL",
        "Literature",
        "Hymns",
        "Divine",
        "Letter-Prayer",
        "Sîn-iddinam to Utu",
    ),
    ("CANONICAL", "Literature", "Hymns", "Royal"),
    ("CANONICAL", "Literature", "Hymns", "Temples"),
    ("CANONICAL", "Literature", "Lamentations"),
    ("CANONICAL", "Literature", "Lamentations", "Balaĝ"),
    ("CANONICAL", "Literature", "Lamentations", "Eršaḫuĝa"),
    ("CANONICAL", "Literature", "Lamentations", "Eršema (Kidudû)"),
    ("CANONICAL", "Literature", "Lamentations", "Eršema (Paired with Balaĝ)"),
    ("CANONICAL", "Literature", "Lamentations", "Kalûtu Catalogue"),
    ("CANONICAL", "Literature", "Lamentations", "Šuʾila (Emesal)"),
    ("CANONICAL", "Literature", "Monologue and dialogue"),
    ("CANONICAL", "Literature", "Monologue and dialogue", "Advice to a Prince"),
    ("CANONICAL", "Literature", "Monologue and dialogue", "Aluzinnu Text"),
    ("CANONICAL", "Literature", "Monologue and dialogue", "Counsels of Wisdom"),
    ("CANONICAL", "Literature", "Monologue and dialogue", "Debate poems"),
    ("CANONICAL", "Literature", "Monologue and dialogue", "Dialogue of Pessimism"),
    ("CANONICAL", "Literature", "Monologue and dialogue", "Fables"),
    (
        "CANONICAL",
        "Literature",
        "Monologue and dialogue",
        "Instructions of Šūpê-amēli (Šimâ milka)",
    ),
    ("CANONICAL", "Literature", "Monologue and dialogue", "Instructions"),
    ("CANONICAL", "Literature", "Monologue and dialogue", "Love"),
    ("CANONICAL", "Literature", "Monologue and dialogue", "Ludlul bēl nēmeqi"),
    ("CANONICAL", "Literature", "Monologue and dialogue", "Monologues"),
    ("CANONICAL", "Literature", "Monologue and dialogue", "Proverbs"),
    (
        "CANONICAL",
        "Literature",
        "Monologue and dialogue",
        "Proverbs",
        "Bilingual Proverbs",
    ),
    ("CANONICAL", "Literature", "Monologue and dialogue", "Scribal"),
    ("CANONICAL", "Literature", "Monologue and dialogue", "Scribal", "Examenstext A"),
    ("CANONICAL", "Literature", "Monologue and dialogue", "Scribal", "Examenstext B"),
    (
        "CANONICAL",
        "Literature",
        "Monologue and dialogue",
        "Scribal",
        "In Praise of Scribal Art",
    ),
    ("CANONICAL", "Literature", "Monologue and dialogue", "Theodicy"),
    ("CANONICAL", "Literature", "Narrative"),
    ("CANONICAL", "Literature", "Narrative", "Adapa"),
    ("CANONICAL", "Literature", "Narrative", "Angim"),
    ("CANONICAL", "Literature", "Narrative", "Anzû"),
    ("CANONICAL", "Literature", "Narrative", "Atraḫasīs (Story of the Flood)"),
    ("CANONICAL", "Literature", "Narrative", "Creation Myth"),
    ("CANONICAL", "Literature", "Narrative", "Cuthaean Legend"),
    ("CANONICAL", "Literature", "Narrative", "Descent of Ištar"),
    ("CANONICAL", "Literature", "Narrative", "Enki and Ninmah"),
    ("CANONICAL", "Literature", "Narrative", "Enūma eliš"),
    ("CANONICAL", "Literature", "Narrative", "Erra and Išum"),
    ("CANONICAL", "Literature", "Narrative", "Etana Epic"),
    ("CANONICAL", "Literature", "Narrative", "Founding of Eridu"),
    ("CANONICAL", "Literature", "Narrative", "Gilgameš"),
    ("CANONICAL", "Literature", "Narrative", "Lugalbanda"),
    ("CANONICAL", "Literature", "Narrative", "Lugal-e"),
    ("CANONICAL", "Literature", "Narrative", "Nergal and Ereškigal"),
    ("CANONICAL", "Literature", "Narrative", "Slaying of Labbu"),
    ("CANONICAL", "Literature", "Narrative", "The Elevation of Babylon"),
    ("CANONICAL", "Literature", "Narrative", "The Poor Man of Nippur"),
    ("CANONICAL", "Literature", "Narrative", "Toil of Babylon"),
    ("CANONICAL", "Literature", "Sidu"),
    ("CANONICAL", "Literature", "Taboo Text (CBS 16 and duplicates)"),
    ("CANONICAL", "Magic"),
    ("CANONICAL", "Magic", "Anti-witchcraft"),
    ("CANONICAL", "Magic", "Anti-witchcraft", "Maqlû"),
    ("CANONICAL", "Magic", "Anti-witchcraft", "Ušburruda"),
    ("CANONICAL", "Magic", "Exorcistic"),
    ("CANONICAL", "Magic", "Exorcistic", "Alan niŋ saŋ ila"),
    ("CANONICAL", "Magic", "Exorcistic", "Asaggiga"),
    ("CANONICAL", "Magic", "Exorcistic", "Bīt mēseri"),
    ("CANONICAL", "Magic", "Exorcistic", "Compendium"),
    ("CANONICAL", "Magic", "Exorcistic", "Ḫulbazizi"),
    ("CANONICAL", "Magic", "Exorcistic", "Lamaštu"),
    ("CANONICAL", "Magic", "Exorcistic", "Marduk’s Address to the Demons (Udugḫul 11)"),
    ("CANONICAL", "Magic", "Exorcistic", "Muššuʾu"),
    ("CANONICAL", "Magic", "Exorcistic", "Saĝba"),
    ("CANONICAL", "Magic", "Exorcistic", "Saggigameš"),
    ("CANONICAL", "Magic", "Exorcistic", "Šēp lemutti"),
    ("CANONICAL", "Magic", "Exorcistic", "Šurpu"),
    ("CANONICAL", "Magic", "Exorcistic", "Tummu bītu"),
    ("CANONICAL", "Magic", "Exorcistic", "Udugḫul"),
    ("CANONICAL", "Magic", "Exorcistic", "Zi-pà-incantation"),
    ("CANONICAL", "Magic", "Purification"),
    ("CANONICAL", "Magic", "Purification", "Bīt rimki"),
    ("CANONICAL", "Magic", "Purification", "Bīt salāʾ mê"),
    ("CANONICAL", "Magic", "Purification", "Mīs pî"),
    ("CANONICAL", "Magic", "Medical"),
    ("CANONICAL", "Magic", "Medical", "Sagalla"),
    ("CANONICAL", "Magic", "Medical", "Šaziga"),
    ("CANONICAL", "Magic", "Varia"),
    ("CANONICAL", "Magic", "Varia", "Baby Ritual"),
    ("CANONICAL", "Magic", "Varia", "Building Rituals"),
    ("CANONICAL", "Magic", "Varia", "Consecration of a Priest"),
    ("CANONICAL", "Magic", "Varia", "Diĝiršadiba"),
    ("CANONICAL", "Magic", "Varia", "Egalkura"),
    ("CANONICAL", "Magic", "Varia", "Kunuk ḫalti"),
    ("CANONICAL", "Magic", "Varia", "Lipšur litany"),
    ("CANONICAL", "Magic", "Varia", "Namburbi"),
    ("CANONICAL", "Magic", "Varia", "Namerimburuda"),
    ("CANONICAL", "Magic", "Varia", "Zuburudabeda"),
    ("CANONICAL", "Other Word Lists"),
    ("CANONICAL", "Other Word Lists", "Alan = lānu"),
    ("CANONICAL", "Other Word Lists", "Igituḫ"),
    ("CANONICAL", "School Tablet"),
    ("CANONICAL", "Technical"),
    ("CANONICAL", "Technical", "Astronomy"),
    ("CANONICAL", "Technical", "Astronomy", "I.NAM.GIŠ.HUR.AN.KI.A"),
    ("CANONICAL", "Technical", "Astronomy", "Almanac"),
    ("CANONICAL", "Technical", "Astronomy", "Normal Star Almanac"),
    ("CANONICAL", "Technical", "Astronomy", "Astrolabe (Three Stars each)"),
    ("CANONICAL", "Technical", "Astronomy", "Astronomical Diaries"),
    ("CANONICAL", "Technical", "Astronomy", "Dalbanna-text"),
    ("CANONICAL", "Technical", "Astronomy", "Giskim Texts (MUL.APIN 3?)"),
    ("CANONICAL", "Technical", "Astronomy", "GU-Text "),
    ("CANONICAL", "Technical", "Astronomy", "MUL.APIN"),
    ("CANONICAL", "Technical", "Astronomy", "Time keeping texts"),
    ("CANONICAL", "Technical", "Astrology"),
    ("CANONICAL", "Technical", "Astrology", "Horoscope"),
    ("CANONICAL", "Technical", "Astrology", "Kalendertext"),
    ("CANONICAL", "Technical", "Astrology", "Micro-zodiac Text"),
    ("CANONICAL", "Technical", "Commentary"),
    ("CANONICAL", "Technical", "Mathematics"),
    ("CANONICAL", "Technical", "Medicine"),
    ("CANONICAL", "Technical", "Medicine", "Babylonian Medical Incantations"),
    ("CANONICAL", "Technical", "Medicine", "Diagnostic and Prognostic"),
    ("CANONICAL", "Technical", "Medicine", "Diagnostic and Prognostic", "Sagig"),
    ("CANONICAL", "Technical", "Medicine", "Kunuk ḫalti"),
    ("CANONICAL", "Technical", "Medicine", "Therapeutic"),
    ("CANONICAL", "Technical", "Medicine", "Therapeutic", "Nineveh Medical Compendium"),
    (
        "CANONICAL",
        "Technical",
        "Medicine",
        "Therapeutic",
        "Nineveh Medical Compendium",
        "I Cranium",
    ),
    (
        "CANONICAL",
        "Technical",
        "Medicine",
        "Therapeutic",
        "Nineveh Medical Compendium",
        "II Eyes",
    ),
    (
        "CANONICAL",
        "Technical",
        "Medicine",
        "Therapeutic",
        "Nineveh Medical Compendium",
        "III Ears",
    ),
    (
        "CANONICAL",
        "Technical",
        "Medicine",
        "Therapeutic",
        "Nineveh Medical Compendium",
        "IV Neck",
    ),
    (
        "CANONICAL",
        "Technical",
        "Medicine",
        "Therapeutic",
        "Nineveh Medical Compendium",
        "V Nosebleed",
    ),
    (
        "CANONICAL",
        "Technical",
        "Medicine",
        "Therapeutic",
        "Nineveh Medical Compendium",
        "VI Teeth",
    ),
    (
        "CANONICAL",
        "Technical",
        "Medicine",
        "Therapeutic",
        "Nineveh Medical Compendium",
        "VII Bronchia",
    ),
    (
        "CANONICAL",
        "Technical",
        "Medicine",
        "Therapeutic",
        "Nineveh Medical Compendium",
        "VIII Stomach",
    ),
    (
        "CANONICAL",
        "Technical",
        "Medicine",
        "Therapeutic",
        "Nineveh Medical Compendium",
        "IX Epigastrum",
    ),
    (
        "CANONICAL",
        "Technical",
        "Medicine",
        "Therapeutic",
        "Nineveh Medical Compendium",
        "X Kidney",
    ),
    (
        "CANONICAL",
        "Technical",
        "Medicine",
        "Therapeutic",
        "Nineveh Medical Compendium",
        "XI Anus",
    ),
    (
        "CANONICAL",
        "Technical",
        "Medicine",
        "Therapeutic",
        "Nineveh Medical Compendium",
        "XII Hamstring",
    ),
    (
        "CANONICAL",
        "Technical",
        "Medicine",
        "Therapeutic",
        "Recipe/Prescription (Šumma amēlu)",
    ),
    ("CANONICAL", "Technical", "Medicine", "Therapeutic", "Ušburruda"),
    ("CANONICAL", "Technical", "Procedures"),
    ("CANONICAL", "Technical", "Procedures", "Diviner’s manual"),
    (
        "CANONICAL",
        "Technical",
        "Procedures",
        "DUB ḪA.LA and the Calculation of the Stipulated Term",
    ),
    ("CANONICAL", "Technical", "Procedures", "Glass Texts"),
    ("CANONICAL", "Technical", "Ritual texts"),
    ("CANONICAL", "Technical", "Ritual texts", "Ikribu"),
    ("CANONICAL", "Technical", "Ritual texts", "Qualifications of Babylonian Diviners"),
    ("MONUMENTAL",),
    ("MONUMENTAL", "Agum-Kakrime Inscription"),
    ("MONUMENTAL", "Building"),
    ("MONUMENTAL", "Dedication"),
    ("MONUMENTAL", "Legal"),
    ("MONUMENTAL", "Legal", "Laws of Ḫammurāpi"),
    ("MONUMENTAL", "Narrative"),
    ("MONUMENTAL", "Representative (personalia)"),
    ("MONUMENTAL", "Seal inscriptions"),
    ("OTHER",),
    ("OTHER", "Fake"),
    ("OTHER", "Uncertain"),
)
