%import .text_line (text_line)
%import .parallel_line (parallel_line)
%import .note_line.note_line
%import .at_line.at_line
%import .translation_line.translation_line
%import .dollar_line (dollar_line)
%import .empty_line (empty_line)
%import .control_line (control_line)

?start: line

?line: empty_line
     | note_line
     | text_line
     | dollar_line
     | at_line
     | parallel_line
     | translation_line
     | control_line

