from ebl.transliteration.domain.signs_transformer import name_arguments


from ebl.transliteration.domain.enclosure_tokens import (
    AccidentalOmission,
    BrokenAway,
    DocumentOrientedGloss,
    IntentionalOmission,
    PerhapsBrokenAway,
    Removal,
    Determinative,
)
from ebl.transliteration.domain.enclosure_type import EnclosureType
from ebl.transliteration.domain.sign_tokens import Reading
from ebl.transliteration.domain.tokens import (
    ErasureState,
    UnknownNumberOfSigns,
    ValueToken,
    Joiner,
)
from ebl.transliteration.domain.unknown_sign_tokens import UnidentifiedSign
from ebl.transliteration.domain.word_tokens import Word

ENCLOSURE_VISITOR_TYPES_CASES_1 = [
    ("...", (Word.of((UnknownNumberOfSigns.of(),)),)),
    (
        "[...]",
        (
            Word.of(
                (
                    BrokenAway.open(),
                    UnknownNumberOfSigns(
                        frozenset({EnclosureType.BROKEN_AWAY}), ErasureState.NONE
                    ),
                    BrokenAway.close().set_enclosure_type(
                        frozenset({EnclosureType.BROKEN_AWAY})
                    ),
                )
            ),
        ),
    ),
    (
        "(...)",
        (
            Word.of(
                (
                    PerhapsBrokenAway.open(),
                    UnknownNumberOfSigns(
                        frozenset({EnclosureType.PERHAPS}), ErasureState.NONE
                    ),
                    PerhapsBrokenAway.close().set_enclosure_type(
                        frozenset({EnclosureType.PERHAPS})
                    ),
                )
            ),
        ),
    ),
    (
        "[(...)]",
        (
            Word.of(
                (
                    BrokenAway.open(),
                    PerhapsBrokenAway.open().set_enclosure_type(
                        frozenset({EnclosureType.BROKEN_AWAY})
                    ),
                    UnknownNumberOfSigns.of().set_enclosure_type(
                        frozenset(
                            {
                                EnclosureType.BROKEN_AWAY,
                                EnclosureType.PERHAPS_BROKEN_AWAY,
                            }
                        )
                    ),
                    PerhapsBrokenAway.close().set_enclosure_type(
                        frozenset(
                            {
                                EnclosureType.BROKEN_AWAY,
                                EnclosureType.PERHAPS_BROKEN_AWAY,
                            }
                        )
                    ),
                    BrokenAway.close().set_enclosure_type(
                        frozenset({EnclosureType.BROKEN_AWAY})
                    ),
                )
            ),
        ),
    ),
    (
        "<(...)>",
        (
            Word.of(
                (
                    IntentionalOmission.open(),
                    UnknownNumberOfSigns.of().set_enclosure_type(
                        frozenset({EnclosureType.INTENTIONAL_OMISSION})
                    ),
                    IntentionalOmission.close().set_enclosure_type(
                        frozenset({EnclosureType.INTENTIONAL_OMISSION})
                    ),
                )
            ),
        ),
    ),
    (
        "<...>",
        (
            Word.of(
                (
                    AccidentalOmission.open(),
                    UnknownNumberOfSigns.of().set_enclosure_type(
                        frozenset({EnclosureType.ACCIDENTAL_OMISSION})
                    ),
                    AccidentalOmission.close().set_enclosure_type(
                        frozenset({EnclosureType.ACCIDENTAL_OMISSION})
                    ),
                )
            ),
        ),
    ),
    (
        "<<...>>",
        (
            Word.of(
                (
                    Removal.open(),
                    UnknownNumberOfSigns.of().set_enclosure_type(
                        frozenset({EnclosureType.REMOVAL})
                    ),
                    Removal.close().set_enclosure_type(
                        frozenset({EnclosureType.REMOVAL})
                    ),
                )
            ),
        ),
    ),
    (
        "{(...)}",
        (
            DocumentOrientedGloss.open(),
            Word.of(
                (
                    UnknownNumberOfSigns.of().set_enclosure_type(
                        frozenset({EnclosureType.DOCUMENT_ORIENTED_GLOSS})
                    ),
                )
            ).set_enclosure_type(frozenset({EnclosureType.DOCUMENT_ORIENTED_GLOSS})),
            DocumentOrientedGloss.close().set_enclosure_type(
                frozenset({EnclosureType.DOCUMENT_ORIENTED_GLOSS})
            ),
        ),
    ),
    (
        "ku[r ...]",
        (
            Word.of(
                (
                    Reading.of_arguments(
                        name_arguments(
                            (
                                ValueToken.of("ku"),
                                BrokenAway.open(),
                                ValueToken(
                                    frozenset({EnclosureType.BROKEN_AWAY}),
                                    ErasureState.NONE,
                                    "r",
                                ),
                            )
                        )
                    ),
                )
            ),
            Word.of(
                (
                    UnknownNumberOfSigns.of().set_enclosure_type(
                        frozenset({EnclosureType.BROKEN_AWAY})
                    ),
                    BrokenAway.close().set_enclosure_type(
                        frozenset({EnclosureType.BROKEN_AWAY})
                    ),
                )
            ).set_enclosure_type(frozenset({EnclosureType.BROKEN_AWAY})),
        ),
    ),
    (
        "{k[ur}-X]",
        (
            Word.of(
                (
                    Determinative.of(
                        (
                            Reading.of_arguments(
                                name_arguments(
                                    (
                                        ValueToken.of("k"),
                                        BrokenAway.open(),
                                        ValueToken(
                                            frozenset({EnclosureType.BROKEN_AWAY}),
                                            ErasureState.NONE,
                                            "ur",
                                        ),
                                    )
                                )
                            ),
                        )
                    ),
                    Joiner.hyphen().set_enclosure_type(
                        frozenset({EnclosureType.BROKEN_AWAY})
                    ),
                    UnidentifiedSign.of().set_enclosure_type(
                        frozenset({EnclosureType.BROKEN_AWAY})
                    ),
                    BrokenAway.close().set_enclosure_type(
                        frozenset({EnclosureType.BROKEN_AWAY})
                    ),
                )
            ),
        ),
    ),
]
