GLOSSARY = (
    "@project test/test_lemmatization\n"
    "@lang    akk\n"
    "@name    akk\n\n"
    "@letter A\n\n"
    "@entry adru [dark] AV\n"
    "@form KAN₅-su $adrūssu\n"
    "@sense AV darkly\n"
    "@end entry\n\n"
    "@entry akālu [eat] V\n"
    "@form KU₂ $akālu\n"
    "@sense V eat\n"
    "@end entry\n\n"
    "@entry antallû [eclipse] N\n"
    "@form AN.KU₁₀ $antallû\n"
    "@sense N eclipse\n"
    "@end entry\n\n"
    "@letter E\n\n"
    "@entry erēbu [enter] V\n"
    "@form KU₄ $erēbu\n"
    "@sense V enter\n"
    "@sense V fall\n"
    "@end entry\n\n"
    "@letter I\n\n"
    "@entry ilu [god] N\n"
    "@form DINGIR $ilu\n"
    "@form DINGIR{MEŠ} $ilu\n"
    "@sense N god\n"
    "@end entry\n\n"
    "@entry ina [in] PRP\n"
    "@form ina $ina\n"
    "@form in $ina\n"
    "@sense PRP in\n"
    "@sense PRP during\n"
    "@sense PRP at (plus numeral)\n"
    "@end entry\n\n"
    "@letter L\n\n"
    "@entry lawi [encircled] AJ\n"
    "@form NIGIN₂ $lawi\n"
    "@form NIGIN $lawi\n"
    "@form NIGIN-ma $lawima\n"
    "@sense V surrounded with\n"
    "@end entry\n\n"
    "@letter R\n\n"
    "@entry tarbaṣu [pen] N\n"
    "@form TUR₃ $tarbaṣa\n"
    "@sense N halo\n"
    "@end entry\n\n"
    "@letter R\n\n"
    "@entry rabû [big] AJ\n"
    "@form GAL $rabû\n"
    "@form GAL-u $rabû\n"
    "@form {LU₂}GAL $rab\n"
    "@sense AJ great\n"
    "@sense AJ large\n"
    "@sense AJ big\n"
    "@end entry\n\n"
    "@entry rabû [set] V\n"
    "@form ŠÚ $rabû\n"
    "@sense V set\n"
    "@end entry\n\n"
    "@letter Š\n\n"
    "@entry šakānu [put] V\n"
    "@form GAR $šakānu\n"
    "@form GAR-ma $šakānu\n"
    "@sense V take place\n"
    "@end entry\n\n"
    "@entry šumma [if] CNJ\n"
    "@form DIŠ $šumma\n"
    "@sense CNJ if\n"
    "@end entry\n\n"
    "@letter U\n\n"
    "@entry ūmu [day] N\n"
    "@form U₄{ME} $ūmu\n"
    "@form UD $ūmu\n"
    "@form ME $ūmu\n"
    "@form U₄ $ūmu\n"
    "@sense N day\n"
    "@sense N first appearance\n"
    "@sense N daytime\n"
    "@end entry"
)

QPN_GLOSSARY = (
    "@letter S\n\n"
    "@entry Sîn [moon(-god)] N\n"
    "@form sin $Sîn\n"
    "@sense N moon\n"
    "@end entry\n\n"
    "@letter Š\n\n"
    "@entry Šabāṭu [Month XI] MN\n"
    "@form ZIZ₂ %akk $Šabāṭu\n"
    "@form {ITU}ZIZ₂ %akk $Šabāṭu\n"
    "@sense MN Month XI\n"
    "@end entry\n\n"
)
